version: 1.0.0
static:
  client: 
    config_interval: 5000
    min_connections_per_node: 5
    max_connections_per_node: 50
    async_min_connections_per_node: 100
    async_max_connections_per_node: 500
dynamic:
  client:
    app_id: unit_tester
    max_error_rate: 22
    rack_ids: [2,4,6,8]
    tend_interval: 500
  read:
    replica: PREFER_RACK
    max_retries: 20
  batch_read:
    max_concurrent_threads: 10
    allow_inline: true
  scan:
    concurrent_nodes: true
    max_concurrent_nodes: 5
    max_retries: 5
  write:
    durable_delete: true
  metrics:
    enable: true
    latency_shift: 2
    latency_columns: 7
    labels:
      region: us-west
      zone: usw1-az3
      rack-id: kjsdfj2k3k